In [2]:
# used for manipulating directory paths
import os

# Scientific and vector computation for python
import numpy as np

# Plotting library
from matplotlib import pyplot

# Optimization module in scipy
from scipy import optimize

# will be used to load MATLAB mat datafile format
from scipy.io import loadmat

# library written for this exercise providing additional functions for assignment submission, and others
import utils

# define the submission/grader object for this exercise
grader = utils.Grader()

# tells matplotlib to embed plots within the notebook
%matplotlib inline

In [5]:
mat = np.array([[1,2,3], [4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [6]:
col = np.array([10,69])
mat[:, 1] = col
print(mat)

[[ 1 10  3]
 [ 4 69  6]]
