In [10]:
import numpy as np 

In [11]:
a = np.random.rand(2,3,3)
b = np.random.rand(2,3,3)
c = (a@b)
d = np.dot(a,b)
print(c,c.shape)

[[[0.30484112 0.28931471 0.85853299]
  [0.31220337 0.6401088  0.89421288]
  [0.38537903 0.57484577 1.06502338]]

 [[0.79553404 0.75879405 0.80446442]
  [0.46480838 0.4261236  0.42275691]
  [0.48788489 0.42568987 0.44553366]]] (2, 3, 3)


In [12]:
print(d,d.shape)

[[[[0.30484112 0.28931471 0.85853299]
   [0.60591609 0.8181888  0.57885303]]

  [[0.31220337 0.6401088  0.89421288]
   [0.96336983 0.89445983 0.98352331]]

  [[0.38537903 0.57484577 1.06502338]
   [0.87021903 0.92992737 0.83972899]]]


 [[[0.27431364 0.52745512 0.77964035]
   [0.79553404 0.75879405 0.80446442]]

  [[0.2396508  0.40093499 0.63041414]
   [0.46480838 0.4261236  0.42275691]]

  [[0.24510856 0.4330818  0.64282065]
   [0.48788489 0.42568987 0.44553366]]]] (2, 3, 2, 3)
